# Generated by Django 3.0.7 on 2020-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200615_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_qty_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
